### ISSUE TITLE
bugs/ui

### ISSUE THREAD

**Issue by artamonJr** [andreylarionovdev/toxin#10]
Dropdown на главной
1. Не должен показываться pointer, когда наводим на поле, только когда на кнопку открытия
2. Я увел мышку с кнопки, а она будто бы наведена
![image](https://user-images.githubusercontent.com/46949445/76092151-f7e3ec80-5fcf-11ea-9314-d76abec62914.png)
3. В макете по идее кнопки должны быть сразу видны когда открываешь дропдаун
4. Когда все count's по нулям кнопка очистить не должна показываться
5. После нажатия на кнопку очистить не дизейблится кнопка -
![image](https://user-images.githubusercontent.com/46949445/76092432-6f198080-5fd0-11ea-933c-816c00be1e76.png)
6. Не считается кол-во гостей
![image](https://user-images.githubusercontent.com/46949445/76092649-ce779080-5fd0-11ea-96d6-4984a29035e0.png)

**Comment by madnessJs** [comment]
Календарь на главной
1. При уменьшении экрана сплющивается число
![image](https://user-images.githubusercontent.com/46949445/76093049-6d03f180-5fd1-11ea-8a43-c7601456b705.png)

**Comment by madnessJs** [comment]
Форма на главной
1. Это не красиво
![image](https://user-images.githubusercontent.com/46949445/76093210-a8062500-5fd1-11ea-8007-5cd567f944c7.png)

**Comment by madnessJs** [comment]
Хедер
Не понятный курсор когда наводишь на итем меню с подменю

**Comment by madnessJs** [comment]
Футер
1. Сливаются блоки меню
![image](https://user-images.githubusercontent.com/46949445/76093888-c4ef2800-5fd2-11ea-963d-9479365a5f20.png)

**Comment by andreylarionovdev** [comment]
> 2. Я увел мышку с кнопки, а она будто бы наведена
>    ![image](https://user-images.githubusercontent.com/46949445/76092151-f7e3ec80-5fcf-11ea-9314-d76abec62914.png)

Что значит “будто бы наведена”? Это стилизованный фокус. Видимо, ты нажал на эту кнопку.

**Comment by andreylarionovdev** [comment]
> 3. Тут тоже нужно переделать, а то остается непонятный эффект
>    ![image](https://user-images.githubusercontent.com/46949445/76094944-878b9a00-5fd4-11ea-89a1-dca4862feaa5.png)

То же самое. "Непонятный" эффект - это стилизованный фокус.

**Comment by andreylarionovdev** [comment]
> 2\. При наведении на заголовки курсор меняется

Да, меняется на текстовый курсор. Не должен изменяться? Почему?

**Comment by madnessJs** [comment]
Эти вопросы сняты, я под вечер смотрел, это нормально)

**Comment by madnessJs** [comment]
Ну вот, намного же приятнее смотреть теперь на разметке, все ясно и понятно)
![image](https://user-images.githubusercontent.com/46949445/76728504-edf88100-6767-11ea-9b77-9a635dca195b.png)

**Comment by madnessJs** [comment]
Календарь на главной
1. 
![image](https://user-images.githubusercontent.com/46949445/76728827-cd7cf680-6768-11ea-89d8-59d2d2231360.png)

**Comment by madnessJs** [comment]
Форма на странице входа
1. Лютый line-height)
![image](https://user-images.githubusercontent.com/46949445/76737939-bfd06c80-677a-11ea-8acf-ed315c540f23.png)
2. При добавлении текста в кнопку происходит это
![image](https://user-images.githubusercontent.com/46949445/76738057-f312fb80-677a-11ea-82ec-ce9c8c4c6595.png)
3. 
![image](https://user-images.githubusercontent.com/46949445/76738146-20f84000-677b-11ea-8a06-23b78076b950.png)

**Comment by madnessJs** [comment]
Главная страница
1. padding'и очень не красиво смотрятся при уменьшении экрана
![image](https://user-images.githubusercontent.com/46949445/76738217-471de000-677b-11ea-8838-95f51498f21b.png)

**Comment by madnessJs** [comment]
Форма на странице регистрации
1. Я могу нажать и на текст, это тоже интерактивный элемент. Исправь по стандартам
![image](https://user-images.githubusercontent.com/46949445/76738411-a2e86900-677b-11ea-9540-d40d95280238.png)
тут также
![image](https://user-images.githubusercontent.com/46949445/76738486-c3b0be80-677b-11ea-9d77-c1bf1604a186.png)
также нужно добавить указатели, что в данный момент я нахожусь на этом инпуте
пример:
![image](https://user-images.githubusercontent.com/46949445/76738613-05da0000-677c-11ea-865e-2562ecc0ab93.png)

2. Это не лейбл поля email) клик на него не должен фокуситься на поле
![image](https://user-images.githubusercontent.com/46949445/76738526-ddea9c80-677b-11ea-9089-fd2e1d8cd685.png)

**Comment by madnessJs** [comment]
Хедер
1. Пропрыгивает навигация с клавиатуры через пункты с подменю
![image](https://user-images.githubusercontent.com/46949445/76738935-931d5480-677c-11ea-9f09-faaffca60ba1.png)

**Comment by madnessJs** [comment]
Форма на странице входа
1.
![image](https://user-images.githubusercontent.com/46949445/76853465-5d509c80-685e-11ea-896d-a1fe6ab37db0.png)

**Comment by madnessJs** [comment]
Фильтр на странице поиска номеров
1. Этот дропдаун должен быть без кнопок и значение инпута меняется сразу при нажатии на + или -
![image](https://user-images.githubusercontent.com/46949445/76854370-0055e600-6860-11ea-8ee2-0f181f99ff5b.png)

**Comment by madnessJs** [comment]
Превьюхи на странице поиска номеров
1. У тебя только один номер реализован на сайте, поэтому с остальных превьюх должны быть либо ссылки-заглушки либо вообще убери ссылки
2. pointer появляется только при наведении на число или стрелку, а должен показываться при наведении на кружок
![image](https://user-images.githubusercontent.com/46949445/76854629-840fd280-6860-11ea-97b0-67850790bd0c.png)
3. Лучше не делать меньше 2-ух колонок превьюх на странице, тк смотрится некрасиво. Даже при показе 12-ти штук, как сейчас, это растягивает правую колонку сильно вниз, а что будет если поменяется кол-во отображаемых превьюх?)
4. Придумай другой способ отображения фильтра на маленьких экранах, выглядит некрасиво)
![image](https://user-images.githubusercontent.com/46949445/76855028-50817800-6861-11ea-8378-bacad74208b6.png)

**Comment by madnessJs** [comment]
Страница одного номера
1. Некрасиво смотрится на маленьком экране
![image](https://user-images.githubusercontent.com/46949445/76855908-2df05e80-6863-11ea-8f0c-eea01d49f406.png)
2. Сжимается при добавлении текста
![image](https://user-images.githubusercontent.com/46949445/76856060-8aec1480-6863-11ea-8cdf-e8ce40d565b0.png)
3. По макету кнопка должна быть с градиентом
![image](https://user-images.githubusercontent.com/46949445/76856298-0b127a00-6864-11ea-9397-883c928005b9.png)
4. Не верно выполнено, не по макету)
![image](https://user-images.githubusercontent.com/46949445/76856356-254c5800-6864-11ea-8fbc-9a38f26235cb.png)
5. Календарь криво отображается
![image](https://user-images.githubusercontent.com/46949445/76856634-b3c0d980-6864-11ea-9ebf-55fda9a9162b.png)
![image](https://user-images.githubusercontent.com/46949445/76856643-b6bbca00-6864-11ea-98e3-cf8c61870f81.png)
6. При добавлении текста получается это
![image](https://user-images.githubusercontent.com/46949445/76856741-ec60b300-6864-11ea-8d5b-03620f063351.png)

**Comment by madnessJs** [comment]
Страница хедеров и футеров
1. Выглядит некрасиво на маленьком экране
![image](https://user-images.githubusercontent.com/46949445/76856926-6a24be80-6865-11ea-9923-01b2efbe51fd.png)

**Comment by madnessJs** [comment]
Страница цветов и шрифтов
1. 
![image](https://user-images.githubusercontent.com/46949445/76856993-8fb1c800-6865-11ea-98c2-baa63ea8b0b5.png)

**Comment by madnessJs** [comment]
Страница карточек
1. Странно как-то. Могу только 1 день выбрать (19), а остальные пропадают по наведению
![image](https://user-images.githubusercontent.com/46949445/76857144-e6b79d00-6865-11ea-8221-e099409002c8.png)

**Comment by madnessJs** [comment]
Страница элементов формы
1. При уменьшении экрана отступы едут)
![image](https://user-images.githubusercontent.com/46949445/76857383-62b1e500-6866-11ea-98a4-9fe1757bb9ba.png)

**Comment by artamonJr** [comment]
Страница одного номера
1. Цвет пункта 'хорошо' разнится с цветом на диаграмме
![image](https://user-images.githubusercontent.com/46949445/77642541-e0fd3e00-6f6e-11ea-9a09-3557a16919ba.png)

**Comment by artamonJr** [comment]
Страница хедеров и футеров
1. Лучше наверное будет отделить меню навигации от меню пользователя мне так кажется
![image](https://user-images.githubusercontent.com/46949445/77642774-405b4e00-6f6f-11ea-83f8-3afeafcd13b4.png)

**Comment by artamonJr** [comment]
![image](https://user-images.githubusercontent.com/46949445/78240507-c8010980-74e7-11ea-8450-dfa206b0d2bb.png)
точки какие-то появились

**Comment by artamonJr** [comment]
Кнопки слиплись
![image](https://user-images.githubusercontent.com/46949445/78240625-ecf57c80-74e7-11ea-8593-f1204315a513.png)

**Comment by andreylarionovdev** [comment]
> ![image](https://user-images.githubusercontent.com/46949445/78240507-c8010980-74e7-11ea-8450-dfa206b0d2bb.png)
> точки какие-то появились

пятнами покрылся

**Comment by artamonJr** [comment]
Выровняй по горизонтали
![image](https://user-images.githubusercontent.com/46949445/78337047-04d90900-7599-11ea-9588-df41f1f21c92.png)

**Comment by artamonJr** [comment]
Нажатие должно быть только по галочке или по ее области(когда есть паддинги к примеру), а на сверху до низу текстового поля
![image](https://user-images.githubusercontent.com/46949445/78764764-b314f200-798f-11ea-9a75-2ad1b6c08337.png)

У кнопок сыпь)
![image](https://user-images.githubusercontent.com/46949445/78768595-d4c4a800-7994-11ea-8504-bc99ab927de4.png)

**Comment by artamonJr** [comment]
Тут дропдаун перекрывает кнопки, не правильно
![image](https://user-images.githubusercontent.com/46949445/78987756-94e9f600-7b37-11ea-95b6-678667d4305c.png)

**Comment by artamonJr** [comment]
Тоже как-то не очень. Может лучше 'Выберите удобства', к примеру?
![image](https://user-images.githubusercontent.com/46949445/79106919-16ca6100-7d7c-11ea-9273-a41faa7d097b.png)

**Comment by andreylarionovdev** [comment]
> Тоже как-то не очень. Может лучше 'Выберите удобства', к примеру?
> ![image](https://user-images.githubusercontent.com/46949445/79106919-16ca6100-7d7c-11ea-9273-a41faa7d097b.png)

Так как в лэйбле уже указано "Удобства номера", мне кажется, это только добавит избыточной информации.

**Comment by artamonJr** [comment]
> Так как в лэйбле уже указано "Удобства номера", мне кажется, это только добавит избыточной информации.

После недавнего изучения темы доступности, могу сказать, что ни я ни ты не были правы)
[Почитай](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) для чего нужен placeholder и выбери верный

"+" не по середине
![image](https://user-images.githubusercontent.com/46949445/81040610-62bc8180-8eb4-11ea-82c2-f91451503047.png)

> Горизонтальные отступы разные у пагинации, выглядит не очень красиво

не исправил

Кнопки прилипают к краям блока
![image](https://user-images.githubusercontent.com/46949445/81041210-ed51b080-8eb5-11ea-95a4-9d7e78f48299.png)

Последний коммент скачет что-то
![Peek 2020-05-05 09-55](https://user-images.githubusercontent.com/46949445/81041478-9a2c2d80-8eb6-11ea-85ee-59850f37e144.gif)

Почему форма по правому краю выровнена? Так и задумано
![image](https://user-images.githubusercontent.com/46949445/81041387-651fdb00-8eb6-11ea-8a35-0619a18e0e66.png)

Отзывы прилипли
![image](https://user-images.githubusercontent.com/46949445/81041530-c21b9100-8eb6-11ea-9b30-cd6f55b6d665.png)

Число в кнопке поехало
![image](https://user-images.githubusercontent.com/46949445/81041578-df505f80-8eb6-11ea-86fa-a4c46b7c3fcc.png)

Подрегулируй отступы между блоками, а то где-то слишком большие, где-то слишком маленькие
![image](https://user-images.githubusercontent.com/46949445/81041677-1888cf80-8eb7-11ea-9738-9ff275bfaaa7.png)
![image](https://user-images.githubusercontent.com/46949445/81041693-1f174700-8eb7-11ea-8950-1a5c20c6fecd.png)

Если у тебя на сайте зарегистрируется человек с такими инициалами, то ему это явно не понравится)
![image](https://user-images.githubusercontent.com/46949445/81042303-808be580-8eb8-11ea-9a41-e82382114439.png)

Тут тоже проблемс
![image](https://user-images.githubusercontent.com/46949445/81042390-ae712a00-8eb8-11ea-8cd7-0e380144ad53.png)

Переполнение
![image](https://user-images.githubusercontent.com/46949445/81042436-cba5f880-8eb8-11ea-83c7-10f62418361b.png)

**Comment by andreylarionovdev** [comment]
> Если у тебя на сайте зарегистрируется человек с такими инициалами, то ему это явно не понравится)
> ![image](https://user-images.githubusercontent.com/46949445/81042303-808be580-8eb8-11ea-9a41-e82382114439.png)

Уверен, этот парень и не такого в жизни повидал, так что тут мы его вряд ли удивим. Но на всякий случай исправил.

**Comment by artamonJr** [comment]
Съехало число в кнопке лайка
![image](https://user-images.githubusercontent.com/46949445/82799642-0d580c80-9e83-11ea-8ee8-5d3c2866c9a4.png)

Горизонтальная полоса прокрутки
![image](https://user-images.githubusercontent.com/46949445/82800121-d2a2a400-9e83-11ea-9132-025c9f577220.png)

Поработай над отзывчивостью страницы элементов формы, чтобы не было таких некрасивых вещей
![image](https://user-images.githubusercontent.com/46949445/82801592-3a59ee80-9e86-11ea-80aa-603b8e21226d.png)
![image](https://user-images.githubusercontent.com/46949445/82801600-3e860c00-9e86-11ea-9c94-69df9e1dec70.png)
![image](https://user-images.githubusercontent.com/46949445/82801612-447bed00-9e86-11ea-890f-d6609665c4cd.png)
Тут отступы
![image](https://user-images.githubusercontent.com/46949445/82801650-5067af00-9e86-11ea-8fa7-b0b1889a19cc.png)

**Comment by andreylarionovdev** [comment]
> Съехало число в кнопке лайка
> ![image](https://user-images.githubusercontent.com/46949445/82799642-0d580c80-9e83-11ea-8ee8-5d3c2866c9a4.png)

Не могу воспроизвести, вот скрин на том же разрешении:

![Screenshot 2020-05-25 at 17 41 58](https://user-images.githubusercontent.com/53269810/82831891-ea951a80-9eb9-11ea-9c75-f93911d36d81.png)

> Горизонтальная полоса прокрутки
> ![image](https://user-images.githubusercontent.com/46949445/82800121-d2a2a400-9e83-11ea-9132-025c9f577220.png)

Тоже не смог воспроизвести, тут неплохо было бы разрешение указать, на котором воспроизводится баг.

**Comment by andreylarionovdev** [comment]
> Тут отступы
> ![image](https://user-images.githubusercontent.com/46949445/82801650-5067af00-9e86-11ea-8fa7-b0b1889a19cc.png)

Можно чуть более развернуто, о каких отступах речь и что с ними не так.

**Comment by artamonJr** [comment]
> Не могу воспроизвести, вот скрин на том же разрешении

И вправду. В firefox все окей у меня. Ладно, оставим пока

> Тоже не смог воспроизвести, тут неплохо было бы разрешение указать, на котором воспроизводится баг

Можно не лениться и подергать окошко самому)) в районе 1210px

> Можно чуть более развернуто, о каких отступах речь и что с ними не так.

Между bullet list и блоком преимуществ. Два разных, по смыслу, блока, а отступы, как будто это один блок
![image](https://user-images.githubusercontent.com/46949445/83258694-685d6c80-a1bf-11ea-93b9-c8f0ea5a2586.png)

Еще небольшие моменты
![image](https://user-images.githubusercontent.com/46949445/83258940-db66e300-a1bf-11ea-908e-7f4c78056541.png)

Между дропдаунами и блоком чекбоксов отступ побольше бы сделать
![image](https://user-images.githubusercontent.com/46949445/83259076-1701ad00-a1c0-11ea-903a-7b6e181f78eb.png)

**Comment by artamonJr** [comment]
У такого типа кнопки есть описанное поведение при hover'e, переделай в соответствии с макетом)
![Peek 2020-06-05 15-22](https://user-images.githubusercontent.com/46949445/83875834-7d4a7a80-a740-11ea-9dd1-593912535e77.gif)

**Comment by artamonJr** [comment]
Кнопка "очистить" не по макету
![image](https://user-images.githubusercontent.com/46949445/84026189-8d0ecc80-a995-11ea-83ff-23b258214dc0.png)

**Comment by skinnynpale** [comment]
Можешь закрывать
