### ISSUE TITLE
basic iteration (html, css, bem)

### ISSUE THREAD

**Issue by artamonJr** [andreylarionovdev/toxin#12]
У тебя лого - фоновая картинка, это не очень правильно, тк лого имеет определенный "вес" (смысл). Фоновые картинки используют, когда смысл блока можно понять без картинки, она как-будто просто украшение, а тут другая история
![image](https://user-images.githubusercontent.com/46949445/83261259-baa08c80-a1c3-11ea-9236-5a1ef4dc5b3f.png)

Почему navigation-item залез в user-navigation? Нужно поправить
![image](https://user-images.githubusercontent.com/46949445/83261461-094e2680-a1c4-11ea-8724-f48e4f58910a.png)

Как думаешь, может убрать класс с боди и 3 дива-контейнера и упростить разметку?
![image](https://user-images.githubusercontent.com/46949445/83261715-7bbf0680-a1c4-11ea-9473-6aeab1b191af.png)

**Comment by andreylarionovdev** [comment]
> Как думаешь, может убрать класс с боди и 3 дива-контейнера и упростить разметку?
> ![image](https://user-images.githubusercontent.com/46949445/83261715-7bbf0680-a1c4-11ea-9473-6aeab1b191af.png)

Ну тут во-первых, футер прижимается к низу более органично в рамках элементов блока, то есть это, как мне кажется, согласуется с БЭМ лучше, чем непосредственное позиционирование блоков (не обернутых в элементы). Во-вторых, боди в некоторых случаях меняет цвет, поэтому удобно этот элемент оформить в качестве блока с модификаторами. Если убрать его здесь, то с большой вероятностью придется добавить ещё один враппер для фона куда-нибудь в лэйаут. В общем, изменить как-нибудь можно, но не думаю что будет лучше в целом.

**Comment by artamonJr** [comment]
Хорошо описал, согласен.

Подправь плиз картинку, чтобы она была более доступна для незрячих пользователей и выполняла best practices для тегов img)
![image](https://user-images.githubusercontent.com/46949445/83736728-b7d9e780-a65a-11ea-9b08-19b09f7132f9.png)

Лучше убрать -range. У тебя вроде только один datepicker
![image](https://user-images.githubusercontent.com/46949445/83737465-b3fa9500-a65b-11ea-89ee-977272693e01.png)

Значение name можно попроще сделать?)
![image](https://user-images.githubusercontent.com/46949445/83737671-ffad3e80-a65b-11ea-97b3-086f35862cae.png)
![image](https://user-images.githubusercontent.com/46949445/83737716-0e93f100-a65c-11ea-9315-b49ccb5610fc.png)

ДД.ММ.ГГГГ. это не value)
![image](https://user-images.githubusercontent.com/46949445/83738150-9843be80-a65c-11ea-9469-badec6da08dd.png)

Тут -group точно нужен?
![image](https://user-images.githubusercontent.com/46949445/83737886-48fd8e00-a65c-11ea-857d-f3a0bfb60b9c.png)

У тебя этот текст сейчас в value хранится, это не верно. При обработке формы у тебя в значении будет не пустая строка, а "Сколько гостей", что не совсем то что должно было бы быть
![image](https://user-images.githubusercontent.com/46949445/83738469-05575400-a65d-11ea-89fb-cab9b4d28e1d.png)

Будет проще воспринимать код, если вначале будет класс dropdown__button, а уже потом классы для js и модификаторы
![image](https://user-images.githubusercontent.com/46949445/83739509-5ca9f400-a65e-11ea-9e8f-52148f77babf.png)

Лучше или не указывать action, либо указать по аналогии со ссылками "mock-adress", тк у тебя нет обработчика формы по адресу "/")
![image](https://user-images.githubusercontent.com/46949445/83739972-ef4a9300-a65e-11ea-826b-cd186909fde3.png)
![image](https://user-images.githubusercontent.com/46949445/83740281-4c464900-a65f-11ea-8d89-f6fa97d7974b.png)

Margin лучше наверное у header прописать, а не у title?)
![image](https://user-images.githubusercontent.com/46949445/83740081-0e492500-a65f-11ea-9d28-b9d54de2dff2.png)

Зачем тут id?
![image](https://user-images.githubusercontent.com/46949445/83740924-2ff6dc00-a660-11ea-83e2-9bf08ad2ddac.png)

**Comment by artamonJr** [comment]
Хорошая работа, молодец!

У тебя сейчас, на элементе висят ненужные атрибуты title, value. Они распирают элемент, его становится неудобно интерпретировать человеку, который изучает код, в частности, в инструментах разработчика и также браузеру приходится делать лишнюю работу. Возможно это и не все минусы, но которые пришли мне в голову сейчас) В pug'е есть [возможность](https://pugjs.org/language/attributes.html#boolean-attributes) условного вывода атрибутов, используй ее
![image](https://user-images.githubusercontent.com/46949445/83876768-0910d680-a742-11ea-8ef8-3194513298fb.png)

Тут сделать, как сделал на странице входа. Единообразие важно)
![image](https://user-images.githubusercontent.com/46949445/83876965-63aa3280-a742-11ea-84f5-713eec490216.png)

Давай приведем подход написания id'шников также к единому стилю? Важно писать код с пониманием того, что ты будешь смотреть на него через некоторое время и, помимо тебя, на код будут смотреть другие люди. Будет странно, если от файла к файлу будет разница стиль кода) Думаю, вполне, можно продублировать содержимое атрибута name в атрибуте id
![image](https://user-images.githubusercontent.com/46949445/83877953-0a430300-a744-11ea-8def-f5ffafde381e.png)

Может выпилить тут -group? Заметил, ты его много где пишешь, почему? Тебе нравится это слово?
![image](https://user-images.githubusercontent.com/46949445/83878200-70c82100-a744-11ea-96d6-17fe606c6e19.png)
![image](https://user-images.githubusercontent.com/46949445/83878889-7c681780-a745-11ea-9f20-a2ae94c1d87d.png)

Мне кажется, что булевые атрибуты лучше размещать в конце тега, так тег проще воспринимается
![image](https://user-images.githubusercontent.com/46949445/83878480-e8964b80-a744-11ea-9257-2bd92f47036c.png)

Тут name поправь тоже плиз
![image](https://user-images.githubusercontent.com/46949445/83878604-17142680-a745-11ea-8263-3e3def415478.png)

И тут тоже, + id атрибуты тоже поправь
![image](https://user-images.githubusercontent.com/46949445/83878782-52aef080-a745-11ea-9c36-52e828afd175.png)

Исправь модификатор
![image](https://user-images.githubusercontent.com/46949445/83879833-f3ea7680-a746-11ea-9976-9cc6d5566daa.png)

*feedback-counter
![image](https://user-images.githubusercontent.com/46949445/83880290-999de580-a747-11ea-92e5-88660abc1405.png)

**Comment by andreylarionovdev** [comment]
> Может выпилить тут -group? Заметил, ты его много где пишешь, почему? Тебе нравится это слово?
> ![image](https://user-images.githubusercontent.com/46949445/83878200-70c82100-a744-11ea-96d6-17fe606c6e19.png)
> ![image](https://user-images.githubusercontent.com/46949445/83878889-7c681780-a745-11ea-9f20-a2ae94c1d87d.png)

Каких-то особых чувств по отношению к данному слову не испытываю, но почему-то кажется уместным называть группу связанных элементов группой) Мы группируем элементы вокруг основного элемента, название/идентификатор которого выносится в название элемента по типу: {идентификатор_основного_элемента_в_группе}-group. Например, в нашем случае, помимо кнопки в группе мог оказаться какой-нибудь label, поясняющий текст и тп. Но именно здесь это немного не в тему, так как элемент один, поэтому исправил.

**Comment by artamonJr** [comment]
> Тут сделать, как сделал на странице входа. Единообразие важно)
![image](https://user-images.githubusercontent.com/46949445/83876965-63aa3280-a742-11ea-84f5-713eec490216.png)

не сделал

Считается плохой практикой писать caps'ом в html. Для таких случаев, лучше использовать средства css
![image](https://user-images.githubusercontent.com/46949445/84026806-a5331b80-a996-11ea-8a96-4a7b09f50c6a.png)

Поправь id в этом поле
![image](https://user-images.githubusercontent.com/46949445/84027293-694c8600-a997-11ea-9bf8-9f7a12388ad1.png)

Лучше придумать другой способ соответствия макету в этой части. Неразрывный пробел использован не по назначению
![image](https://user-images.githubusercontent.com/46949445/84028204-fcd28680-a998-11ea-9dd2-679e44b9c184.png)

У тебя изначально правильно вроде было... Тут лучше desk вместо table
![image](https://user-images.githubusercontent.com/46949445/84029010-62734280-a99a-11ea-99b0-49baf2952741.png)

Зачем 4 img?
![image](https://user-images.githubusercontent.com/46949445/84029414-04932a80-a99b-11ea-8e81-8dd19243c053.png)

Не очень как-то название класса, подумай над другим
![image](https://user-images.githubusercontent.com/46949445/84029875-c6e2d180-a99b-11ea-8159-bd36bfc4ded2.png)

Нужно поменять названия картинок. Не нужно привязываться к месторасположению картинок
Также, нужно поменять alt на более подходящий
Также исправь картинки в соответствии с [пунктом](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/includeFiles.md) в стандартах
![image](https://user-images.githubusercontent.com/46949445/84030105-204b0080-a99c-11ea-84a6-23f2a921b995.png)

Зачем тут font-size и height?
![image](https://user-images.githubusercontent.com/46949445/84030696-2392bc00-a99d-11ea-80a9-eced7fcfbe28.png)

Переименуй название класса
![image](https://user-images.githubusercontent.com/46949445/84031036-a7e53f00-a99d-11ea-8dfd-aa317cc715c8.png)

Лучше наверное copyright-area
![image](https://user-images.githubusercontent.com/46949445/84031114-ce0adf00-a99d-11ea-8f44-2eb89efc4507.png)

Точно нужна доп. прослойка .room-details-page__room-book  ?
![image](https://user-images.githubusercontent.com/46949445/84031231-fb578d00-a99d-11ea-8e5a-67f1b9c8b7ed.png)

Можно классы местами поменять?
![image](https://user-images.githubusercontent.com/46949445/84034086-86d31d00-a9a2-11ea-8eb2-62ced1a2e7fa.png)

Измени класс
![image](https://user-images.githubusercontent.com/46949445/84034336-dca7c500-a9a2-11ea-97f0-ed1b5d12c3d5.png)

Думаю тут не нужно добавлять класс. Ты же через js вставляешь число?
![image](https://user-images.githubusercontent.com/46949445/84034741-6d7ea080-a9a3-11ea-8490-9789b19d71ef.png)

Подходящего плагина для реализации donut не нашел?
Насколько помню, dashoffset поворачивает границу, rotate поворачивает элемент. Может можно обойтись одним из двух способов?
![image](https://user-images.githubusercontent.com/46949445/84036687-38c01880-a9a6-11ea-83cb-18abf9655fd4.png)

*feedback
![image](https://user-images.githubusercontent.com/46949445/84037673-91dc7c00-a9a7-11ea-84a5-d3dd2b0d1326.png)

Это не глобальный счетчик для страницы
![image](https://user-images.githubusercontent.com/46949445/84037878-dec05280-a9a7-11ea-94ad-146cf7380027.png)

Измени alt
Также исправь картинки в соответствии с [пунктом](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/includeFiles.md) в стандартах
![image](https://user-images.githubusercontent.com/46949445/84038040-0dd6c400-a9a8-11ea-97a9-6d5ea36f1ac9.png)

**Comment by andreylarionovdev** [comment]
> Насколько помню, dashoffset поворачивает границу, rotate поворачивает элемент. Может можно обойтись одним из двух способов?

В общем, как это устроено: каждый сегмент - circle.  Длина сегмента изначально равна полной длине окружности (stroke-dasharray=2 * Pi * radius). stroke-dashoffset задает сдвиг - ту точку на окружности, где начинается сегмент. Точку на окружности, где сегмент заканчивается, при помощи stroke-dashoffset задать нельзя, то есть, все сегменты завершаются в одной точке. Для того, чтобы сегменты не перекрывали друг друга, мы вычисляем rotate для каждого сегмента. Другими словами, stroke-dashoffset в нашем случае задаёт длину сегмента, а rotate - его положение на окружности на основании отношения числа отзывов, соответствующих данному сегменту, к общему числу отзывов.

**Comment by artamonJr** [comment]
> 
![image](https://user-images.githubusercontent.com/46949445/85123007-25c40880-b230-11ea-8dad-aec426ffff59.png)

Оу, круто сделал, молодец, я, до этого, не сталкивался с обработкой форм. Сейчас немного понял принцип работы, спасибо!)

alt и название для картинок очень удачно подобрал, молодец
![image](https://user-images.githubusercontent.com/46949445/85123315-b69ae400-b230-11ea-9cd1-3b48b6d0616d.png)

> В общем, как это устроено: каждый сегмент - circle

Ты сам эту логику напилил?

Обычно такие вещи как bullet's делаются псевдоэлементами. Почему выбрал этот подход?
![image](https://user-images.githubusercontent.com/46949445/85124524-b4d22000-b232-11ea-9005-27d602109de2.png)

Count - verb, нужно изменить
![image](https://user-images.githubusercontent.com/46949445/85124622-e0eda100-b232-11ea-9076-12d1eb4d2f6b.png)

Margin, тут, не должен рассматриваться как отступ от последнего комментария до блока, это неверно. Наиболее подходящим, является определение нижнего отступа от всего блока комментариев(section.feedback).
![Снимок экрана от 2020-06-19 13-45-48](https://user-images.githubusercontent.com/46949445/85124864-46da2880-b233-11ea-9bda-d3ab0c9ef8ea.png)

Count - verb
![image](https://user-images.githubusercontent.com/46949445/85125346-21015380-b234-11ea-8ce4-2b744ed16ec6.png)

Нужно убрать неразрывный пробел
![image](https://user-images.githubusercontent.com/46949445/85125386-34acba00-b234-11ea-8838-c168309c2e4a.png)

Ну тут для буллета два тега это жирно конечно, нужно упростить
![image](https://user-images.githubusercontent.com/46949445/85125472-5f970e00-b234-11ea-93ee-c558ba6e2c79.png)

Имя элемента не может быть глаголом
![image](https://user-images.githubusercontent.com/46949445/85125548-7e95a000-b234-11ea-9c8d-407e65d0d3cf.png)
![image](https://user-images.githubusercontent.com/46949445/85125606-98cf7e00-b234-11ea-9fd3-c23f4a2fef10.png)

Можно во всех дропдаунах убрать дата атрибуты и обойтись только классом type?
![image](https://user-images.githubusercontent.com/46949445/85125905-185d4d00-b235-11ea-9a31-8b46213e2bb7.png)

В вопросах у junior-1 у нас есть этот момент: нельзя вкладывать блок в этот же блок. Скорее всего, это - признак плохой архитектуры компонента и компонент нуждается в упрощении
![image](https://user-images.githubusercontent.com/46949445/85126202-a9342880-b235-11ea-89ef-51af562d42b5.png)
Нужно упростить

От пустого элемента нужно избавиться
![image](https://user-images.githubusercontent.com/46949445/85126904-12686b80-b237-11ea-86c3-831fe6d506cd.png)

Ключ модификатора content не подходит. Ты используешь ключ, что менять стили(тему), а не добавлять content, в зависимости от модификатора
![image](https://user-images.githubusercontent.com/46949445/85126986-3c219280-b237-11ea-9553-9e3a2d4495a8.png)

Убери -row
![image](https://user-images.githubusercontent.com/46949445/85127051-5b202480-b237-11ea-8fa4-703e75bed5fb.png)

**Comment by andreylarionovdev** [comment]
> > В общем, как это устроено: каждый сегмент - circle
> 
> Ты сам эту логику напилил?

Напилил сам, да. Идею и расчёты взял здесь: https://css-tricks.com/building-a-donut-chart-with-vue-and-svg/

**Comment by andreylarionovdev** [comment]
> Оу, круто сделал, молодец, я, до этого, не сталкивался с обработкой форм. Сейчас немного понял принцип работы, спасибо!)

Ну там GET в method прописан, поэтому он валит все параметры в адресную строку. Их бы по идее распарсить и фильтр в форме заполнить этими значениями. Но как-нибудь потом, на этой неделе не успеваем) И, кстати, хорошо что name нормальные добавили, а то с пустыми бы не очень смотрелось.

**Comment by skinnynpale** [comment]
Почему то в search-room перестал работать поля с датой пребывания в отеле

**Comment by skinnynpale** [comment]
Как то странно назван класс смотря на его тег 
![image](https://user-images.githubusercontent.com/52371356/87122120-71595780-c2ae-11ea-8bb7-a4461e982da0.png)

**Comment by skinnynpale** [comment]
type_show-filter, как по мне очень странно, может лучше будет action_show-filter или придумать что нибудь другое после type
![image](https://user-images.githubusercontent.com/52371356/87122561-5509ea80-c2af-11ea-980c-97349a45415d.png)

**Comment by skinnynpale** [comment]
Может ли быть размер жидким?
![image](https://user-images.githubusercontent.com/52371356/87122718-aa45fc00-c2af-11ea-9fb7-d9ef2e15d5c2.png)

**Comment by skinnynpale** [comment]
checkbox-expandable-list или checkbox-dropdown-list
![image](https://user-images.githubusercontent.com/52371356/87123635-5cca8e80-c2b1-11ea-9f8b-7f457e568e64.png)

**Comment by skinnynpale** [comment]
Думаю стоит поменять тег div на article для room-thumbnail. Как раз в этом теге можно использовать `header` и `footer`. Подробнее https://htmlacademy.ru/courses/299/run/9?utm_source=google&utm_medium=cpc&utm_campaign=DSA_rf_07.20_9730782229&keyword=&gclid=Cj0KCQjwgJv4BRCrARIsAB17JI7yzDYeErgLohYbtXj5_14EL6cFn9Wnv1jSRN2cnB9wj7_lvCVHOVcaAg3yEALw_wcB
![image](https://user-images.githubusercontent.com/52371356/87124421-f8103380-c2b2-11ea-85b6-31f1ce62eae9.png)

**Comment by skinnynpale** [comment]
Немогу посмотреть info в responsive mode 
![image](https://user-images.githubusercontent.com/52371356/87147667-3ae40280-c2d7-11ea-9ade-b6fe4a7fa845.png)

**Comment by skinnynpale** [comment]
Думаю theme тут не очень подходит, можно сделать with как ключ
![image](https://user-images.githubusercontent.com/52371356/87147940-b5ad1d80-c2d7-11ea-9c1d-7ba5526676fd.png)

**Comment by skinnynpale** [comment]
По всему проекту у тебя есть id-шники, их нужно все убрать, это плохая практика.

**Comment by skinnynpale** [comment]
Сюда и в rating падают id-шники, но там они не испольузются
```
 +radio-button({
              id: 'field-gender-male',
```

**Comment by skinnynpale** [comment]
Можешь закрывать
