### ISSUE TITLE
detailed iteration (html/pug, css/scss, bem, js)

### ISSUE THREAD

**Issue by artamonJr** [andreylarionovdev/toxin#13]

**Comment by skinnynpale** [comment]
Я думаю их можно заменить на константы, в ближайший файл const.js засунуть

```
  this.classExpanded = 'dropdown_expanded';
  this.classClearButtonHidden = 'dropdown__clear-button_hidden';
  this.classCountButtonDisabled = 'dropdown__counter-button_disabled';

  this.selectorMenu = '.js-dropdown__list';
  this.selectorMenuItem = '.js-dropdown__list-item';
  this.selectorCountButton = '.js-dropdown__counter-button';
  this.selectorDecCountButton = '.js-dropdown__counter-button_type_dec';
  this.selectorCount = '.js-dropdown__counter';
```

**Comment by skinnynpale** [comment]
`$counts.each((i, o) => $(o).text(0));`  задай имена чтобы было понятно пожалуйста, везде по дропдауну такое, и еще видел n тоже опиши

**Comment by skinnynpale** [comment]
`'favorite_border'` неправильный модификатор

**Comment by skinnynpale** [comment]
Почему константы не в стиле UPPER_CASE_SNAKE_CASE ?

**Comment by skinnynpale** [comment]
> Я думаю их можно заменить на константы, в ближайший файл const.js засунуть
> 
> ```
>   this.classExpanded = 'dropdown_expanded';
>   this.classClearButtonHidden = 'dropdown__clear-button_hidden';
>   this.classCountButtonDisabled = 'dropdown__counter-button_disabled';
> 
>   this.selectorMenu = '.js-dropdown__list';
>   this.selectorMenuItem = '.js-dropdown__list-item';
>   this.selectorCountButton = '.js-dropdown__counter-button';
>   this.selectorDecCountButton = '.js-dropdown__counter-button_type_dec';
>   this.selectorCount = '.js-dropdown__counter';
> ```

Почему константы не в стиле UPPER_CASE_SNAKE_CASE ?

**Comment by skinnynpale** [comment]
Необходимо исправить по всему проекту такие случаи. Внешнее позиционирование задавать можно только оберткам, нельзя вот так брать и трогать чужой класс.

![photo_2020-07-16_14-34-18](https://user-images.githubusercontent.com/52371356/87695991-e2aa7600-c798-11ea-941f-c9291864d35f.jpg)

**Comment by skinnynpale** [comment]
Лучше всего передавать классы от самой странце где используются и уже на них навешивать цвета

```
&_theme {
    &_dark-100 {
      #{$blockClass}__color {
        background-color: $color-primary-100;
      }
    }

    &_dark-75 {
      #{$blockClass}__color {
        background-color: $color-primary-75;
      }
    }

    &_dark-50 {
      #{$blockClass}__color {
        background-color: $color-primary-50;
      }
    }

    &_dark-25 {
      #{$blockClass}__color {
        background-color: $color-primary-25;
      }
    }

    &_dark-5 {
      #{$blockClass}__color {
        background-color: $color-primary-5;
      }
    }

    &_purple {
      #{$blockClass}__color {
        background-color: $color-purple;
      }
    }

    &_green {
      #{$blockClass}__color {
        background-color: $color-green;
      }
    }   
  }
```

**Comment by skinnynpale** [comment]
Можешь закрывать
