### ISSUE TITLE
project structure

### ISSUE THREAD

**Issue by artamonJr** [andreylarionovdev/toxin#3]
1. У тебя сейчас для всех страниц один css и js. Нужно, чтобы для каждой страницы грузились разные css, js файлы и в этих файлах были подгружены только те стили, к примеру, которые используются на данной странице
2. Файл postcss.config вынести в корень проекта
3. favicon лучше вынести отдельной папкой
4. Папку js в корне лучше назвать utilities и туда выносить всякие разные фичи, которые используются глобально по проекту
5. Картинки разнести по папкам, где они используются. Если это глобальные картинки, то оставить
6. Не соблюден пункт в папке fonts
![image](https://user-images.githubusercontent.com/46949445/74327071-951a7f00-4d9c-11ea-8f34-ce77e2dcef32.png)

**Comment by madnessJs** [comment]
Если папка называется landing, к примеру, то в ней лежат файлы с названием landing
![image](https://user-images.githubusercontent.com/46949445/74630990-d5974580-516c-11ea-91d2-980309ac70cd.png)

**Comment by madnessJs** [comment]
Не понятно содержимое из названия файла config.scss в utils

**Comment by andreylarionovdev** [comment]
4. Страницы UI Kit (страницы без header и footer) также наследуют base напрямую, не только page. Page расширяет base хэдером и футером, и потом его наследуют страницы.

**Comment by madnessJs** [comment]
> 1. Страницы UI Kit (страницы без header и footer) также наследуют base напрямую, не только page. Page расширяет base хэдером и футером, и потом его наследуют страницы.

Ну хорошо, это имеет место быть я думаю)

**Comment by madnessJs** [comment]
Вот этому не место в папке pages
![image](https://user-images.githubusercontent.com/46949445/75034002-43b97080-54bd-11ea-9fc7-c9fd038cb0b6.png)
А файл auth я предлагаю вообще убрать, это излишне. У тебя уже есть шаблон для наследования - page

**Comment by madnessJs** [comment]
В каждой папке только файлы с названием папки
![image](https://user-images.githubusercontent.com/46949445/75034238-d823d300-54bd-11ea-890a-5dd8236d73d4.png)

**Comment by madnessJs** [comment]
Не понятно зачем 2 календаря в компонентах, если он у тебя одинаковый? Нужно 1 оставить
![image](https://user-images.githubusercontent.com/46949445/76090490-bb62c180-5fcc-11ea-9175-8d8fbea8a203.png)

Компонент paginator лучше назвать pagination

Объедини toggle-button и checkbox, тк тогл по своей сути чекбокс

Вот этого не надо) Где нужно несколько checboxes просто вставляй компонент checkbox
![image](https://user-images.githubusercontent.com/46949445/76090788-3d52ea80-5fcd-11ea-80be-c47e66889823.png)

**Comment by andreylarionovdev** [comment]
> Вот этого не надо) Где нужно несколько checboxes просто вставляй компонент checkbox
> ![image](https://user-images.githubusercontent.com/46949445/76090788-3d52ea80-5fcd-11ea-80be-c47e66889823.png)

А можешь объяснить плиз, какие преимущества от этого? Я пока вижу минус в том, что пришлось продублировать стили на две страницы: маржины все эти на чекбоксы, на лэйбл для листа, плюс модификаторы маржинов для рич чекбоксов. Сделал это, но в отдельной ветке, можно потом вмержить в мастер.

**Comment by madnessJs** [comment]
> > Вот этого не надо) Где нужно несколько checboxes просто вставляй компонент checkbox
> > ![image](https://user-images.githubusercontent.com/46949445/76090788-3d52ea80-5fcd-11ea-80be-c47e66889823.png)
> 
> А можешь объяснить плиз, какие преимущества от этого? Я пока вижу минус в том, что пришлось продублировать стили на две страницы: маржины все эти на чекбоксы, на лэйбл для листа, плюс модификаторы маржинов для рич чекбоксов. Сделал это, но в отдельной ветке, можно потом вмержить в мастер.

У тебя по сути 1 компонент - checkbox, а не checkbox-list, checkbox-еще, что-то. Это упрощает понимание кода и его количество, во-первых. Во-вторых никаких дублирований не должно быть, у тебя все стили лежать в компоненте checkbox. Где нужно ты циклом можешь вывести checboxes и все. А марджинами разбивать итемы checkbox это нормально, для каждой страницы возможны разные отступы.

**Comment by andreylarionovdev** [comment]
> Это упрощает понимание кода и его количество, во-первых.

Ну не знаю, компонент checkbox-list, который принимает массив объектов - по-моему, всё ясно. Если интересны детали реализации, то можно одним кликом перейти в компонент и ознакомиться. Количество кода - его стало больше (дублирование html блока на две страницы)

> Во-вторых никаких дублирований не должно быть, у тебя все стили лежать в компоненте checkbox.

Так я не про стили чекбоксов, а про margin, которые в checkbox не могут находиться - margin чекбоксов, margin рич чекбоксов, margin заголовка - они одинаковые для двух страниц и могли бы лежать в одном блоке.  А так получается их надо прописывать в двух блоках (страницах).

Ну да ладно, там кода не так много, так что, думаю, не критично, исправил.

**Comment by artamonJr** [comment]
А если у тебя появится такое, что отступы станут разные на страницах? Или появится 1 страница, где будут другие отступы? Тут уже твое решение не прокатит. А когда у тебя один компонент checkbox и ты на разных страницах через отступы элементов делаешь отступы твоя верстка становится более гибкой

**Comment by artamonJr** [comment]
1. rate-bar лучше переименовать в rating, например
2. плохое название логотипа
![image](https://user-images.githubusercontent.com/46949445/77644985-04c28300-6f73-11ea-90cd-449a3a85127a.png)
3. Почему ты не занес в app.scss свой файл с миксинами, а начал подключать его в разных файлах?
4. Почему тут не подключить app.scss, в котором уже импортнуты vars и fonts?
И вообще сказанное из 4 пункта можно применить точечно к каждой странице, тк это глобальные вещи, которые распространяются на всю страницу. А не перегружать каждый компонент импортами шрифтов и тд)

**Comment by andreylarionovdev** [comment]
> Смотри, касаемо твоей функции-хелпера createBemClasses) В достаточно много ошибок, начиная от деструктуризации объекта заканчивая двойными условиями в if. Тут дело за тобой, либо будем тратить время на ее переделки, либо использовать либу(которой мы сами пользуемся в проектах) под названием bem-cn

Давай-ка попробую исправить для начала. Если дело касается только времени, подозреваю, что на переход к bem-cn его уйдет больше, чем на стайл фиксы в моем хелпере. Если же это вопрос принципиальный - то ок, перепишем на bem-cn.

> Тоже самое относится и к formatCurrency. В ней правда ошибок поменьше, но тоже есть. Нафига она тебе?) У тебя и так все в рублях) лишний скоуп работ просто себе заработаешь)

Да там же не в рублях дело, а в этом пробеле, которым отделяются тысячи. Можно было, конечно, сделать статикой эти все цены, влепить пробел, но я сделал так, что миксин блока принимает на вход численные параметры: 
![Screenshot 2020-04-01 at 20 21 36](https://user-images.githubusercontent.com/53269810/78184381-b5e08600-7469-11ea-93a1-64c50e2a3da5.png)
и далее рассчитывает суммы - умножает цену на кол-во дней, вычитает скидку, добавляет комиссию. А потом полученные суммы надо отформатировать как currency, только вместо запятой/точки нужно отделить тысячи пробелом.

> В ней правда ошибок поменьше, но тоже есть.

Блин, там две строки) думаю, справимся) Линтер не светит, по стандартам пробежался - вроде всё нормально.

> Чем ты руководствовался при подборе названий к переменным screen sizes? Откуда инфа, что 1200px это мин ширина на десктопе, к примеру?

Подглядел у bootstrap: https://www.w3schools.com/bootstrap/bootstrap_grid_system.asp

> И цвет color-dark лучше заменить на color-(имя для главного цвета)

Ребусы) заменить color-dark-100, color-dark-50 и тд на color-primary-50, color-primary-100?

**Comment by andreylarionovdev** [comment]
> А если у тебя появится такое, что отступы станут разные на страницах? Или появится 1 страница, где будут другие отступы? Тут уже твое решение не прокатит. А когда у тебя один компонент checkbox и ты на разных страницах через отступы элементов делаешь отступы твоя верстка становится более гибкой

В таком случае и использовать более мелкий элемент - checkbox. Либо ввести модификатор. Но пока этого не случилось, это больше похоже на преждевременную оптимизацию.

**Comment by artamonJr** [comment]
> > А если у тебя появится такое, что отступы станут разные на страницах? Или появится 1 страница, где будут другие отступы? Тут уже твое решение не прокатит. А когда у тебя один компонент checkbox и ты на разных страницах через отступы элементов делаешь отступы твоя верстка становится более гибкой
> 
> В таком случае и использовать более мелкий составной блок - checkbox. Либо ввести модификатор. Но пока этого не случилось, это больше похоже на преждевременную оптимизацию.

Просто я считаю, что не может как такового компонента checkbox-list. Компонент checkbox самодостаточен и где нужно сделать список чекбоксов, там вставляются эти компоненты списком. Про модификатор хорошая идея, можно и так сделать

**Comment by artamonJr** [comment]
3 и 4 пункты. Окей, согласен выпили только 3 строчку из компонентов страниц. Тк этот файл у тебя подключается в js файлы страниц 
![image](https://user-images.githubusercontent.com/46949445/78242363-8887ec80-74ea-11ea-9e07-cb6e1a95c27e.png)

5 и 6 пункты. Нет конечно, не принципиально) Дело твое, я просто предложил. Почему в этом месте не получать цену строкой, а не числом и просто сюда вставить. Ты тут дополнительные вещи какие-то юзаешь)
![image](https://user-images.githubusercontent.com/46949445/78242877-78244180-74eb-11ea-8a17-c576aaf58b61.png)
Просто, запомни, код должен быть не только рабочим, но еще и хорошо читаться. В стандартах по этому пункту есть описание. Т.е. ты можешь и так оставить, но вопрос, зачем? Если можно сделать в несколько раз проще и читабельнее.

По 7 пункту окей, отлично, вопрос снят)

Да)
![image](https://user-images.githubusercontent.com/46949445/78243195-00a2e200-74ec-11ea-810e-ee6b156a1aa3.png)

По цветам еще одна вещь. У тебя не должно быть неизвестных цветов. Все цвета должны быть вынесены в переменные
![image](https://user-images.githubusercontent.com/46949445/78243444-75761c00-74ec-11ea-82ab-9a136da0a788.png)


з.ы. По этому че-то нифига не понял)
![image](https://user-images.githubusercontent.com/46949445/78243093-c9cccc00-74eb-11ea-8f95-6f6cc8e0f49e.png)

**Comment by andreylarionovdev** [comment]
> з.ы. По этому че-то нифига не понял)
> ![image](https://user-images.githubusercontent.com/46949445/78243093-c9cccc00-74eb-11ea-8f95-6f6cc8e0f49e.png)

![Screenshot 2020-04-02 at 15 49 08](https://user-images.githubusercontent.com/53269810/78259646-4320ea80-74fd-11ea-94fc-dadbf94b812f.png)
![Screenshot 2020-04-02 at 16 01 47](https://user-images.githubusercontent.com/53269810/78259880-8bd8a380-74fd-11ea-86c5-653472964db1.png)

> Почему в этом месте не получать цену строкой, а не числом и просто сюда вставить. Ты тут дополнительные вещи какие-то юзаешь)

Потому что в таком случае эти параметры не получится в формуле использовать (см. скрин выше). Ну и потом нужно будет полученные суммы форматировать. А так да, можно было добавить два дополнительных строковых параметра: totalBrutto и totalNetto и работать просто со строками без всяких формул и форматирований. Но, по-моему,  formatCurrency вполне читаемо и отражает смысл происходящего. Эту функция также можно было бы использовать, если бы добавился функционал на js: например, я выбираю даты в дэйтпикере, скрипт берёт количество дней и пересчитывает суммы, потом форматирует их для отображения используя эту функцию. Короче, я думаю, что функция полезная, не такая сложная для восприятия и могла бы пригодиться, но, проще, конечно сделать строками.

**Comment by artamonJr** [comment]
Окей, хорошо расписал, молодец)

**Comment by artamonJr** [comment]
Давай чтобы html, css, js имели одинаковые названия?
![image](https://user-images.githubusercontent.com/46949445/84037217-f0552a80-a9a6-11ea-80c9-e6bf8c0f8991.png)

**Comment by skinnynpale** [comment]
Можешь закрывать
