### ISSUE TITLE
pp

### ISSUE THREAD

**Issue by artamonJr** [andreylarionovdev/toxin#4]
![image](https://user-images.githubusercontent.com/46949445/74327397-2ee22c00-4d9d-11ea-9318-645e811f0bf5.png)
![image](https://user-images.githubusercontent.com/46949445/74327364-1b36c580-4d9d-11ea-8911-b0dc1d0b8f68.png)
Много замечаний приходится оставлять из-за того, что ты не отрефакторил все по стандартам(
Пробегись еще раз по стандартам и отрефактори код)

**Comment by andreylarionovdev** [comment]
У меня на разрешении 1440x всё не так плохо :) Почему именно 1440px? Отталкиваясь от стандартов: 

> ... Используем **pixel-perfect**, если заказчик предоставил макет;

и все макеты с единичным множителем  по умолчанию экспортируются шириной в 1440px, то и видеть максимальное сходство между макетом и готовой страницей, возможно, ожидают на похожем разрешении. В общем, порядок действий был следующим:

1. В фигме выбрал макет, сделал экспорт с множителем 1x.
2. Обратил внимание, что ширина экспортированного изображения 1440px.
3. Вспомнил, что ширина экрана моей машины тоже 1440px.
4. Включил Pixel Perfect, добавил экспортированный макет.
5. НЕ изменял значения по умолчанию осей X Y, так как ширина изображения равна ширине окна браузера.
6. Начал верстать.
7. Ограничил максимальную ширину контента в 1920px, минимальную в 320px, как рекомендовано в задании к проекту в ризоме, подобрал ширину в процентах для блока контента, выровнял блок по центру.
8. При изменении ширины добавлял media queries (при необходимости, если что то где то ломается или не влазит), но чаще здесь grid делает всё сам. Таким образом выполняется требование о том, что страницы должны быть responsive.

Если ширина экрана не 1440px, то можно выставить временно разрешение 1440px и поглядеть. Возможно, будут мешать скроллбары хрома, которые в некоторых ОС могут двигать контент. Можно добавить overflow: hidden на body и в таком случае будет достигнуто максимальное сходство.

**Comment by madnessJs** [comment]
Заказчик - fsd, макет - toxin. Твой макет должен подстраиваться под запросы людей, а не наоборот. Люди не будут менять разрешение экрана, чтобы посмотреть на твой сайт. Они просто уйдут и все. Форма выглядит ужасно на 1920 ширине, а если у человека 4к монитор...)
'максимальное сходство между макетом и готовой страницей, возможно, ожидают на похожем разрешении' - возможно, но на других разрешениях должно быть читаемо также

**Comment by madnessJs** [comment]
Как все отрефакторишь, отпишись плиз в телеграм

**Comment by andreylarionovdev** [comment]
> а если у человека 4к монитор...)

максимальная ширина контента ограничена 1920px, как я уже писал выше.

> возможно, но на других разрешениях должно быть читаемо также

ну вот я посмотрел сейчас на 1920 - точно всё читаемо, но немного вытягиваются отдельные элементы, с этим согласен.

Если я всё правильно понял, ты предлагаешь ограничить максимальную ширину страницы шириной макета. В таком случае, я не понимаю зачем в требовании к проекту в ризоме указана следущая рекомендация:

> Можно максимальной ширину сделать 1920, а минимальной 320, а между этими значениями подстраиваться под ширину страницы.

Ну ок, давай попробуем, может действительно будет лучше.

> Как все отрефакторишь, отпишись плиз в телеграм

Окей

**Comment by madnessJs** [comment]
Нет)
В общем. У тебя должна быть мин ширина страницы 320, макс 1920. А pixel perfect совпадать с картинкой макета на ширине 1440.
И в этих пределах должно быть все читаемо. А у тебя форма растягивается при ширине 1920.
Понятно?

**Comment by madnessJs** [comment]
Не все поправил, смотри внимательнее(

**Comment by madnessJs** [comment]
Не все
![image](https://user-images.githubusercontent.com/46949445/75036401-d14b8f00-54c2-11ea-9a30-3e30ae4be612.png)

**Comment by madnessJs** [comment]
![image](https://user-images.githubusercontent.com/46949445/75449633-5bda3580-597e-11ea-99c1-49fe8b49b409.png)

**Comment by madnessJs** [comment]
оставим pp до лучших времен)

**Comment by madnessJs** [comment]
![image](https://user-images.githubusercontent.com/46949445/75982026-c0554180-5ef6-11ea-96b0-f8a91ee833e1.png)

**Comment by madnessJs** [comment]
Тут в целом вроде норм, немного подправить и окей. Но сделай чтобы и логотип был тоже в pp
![image](https://user-images.githubusercontent.com/46949445/75982397-a0724d80-5ef7-11ea-9b14-49fd65defcd2.png)

**Comment by madnessJs** [comment]
![image](https://user-images.githubusercontent.com/46949445/76089240-5c03b200-5fca-11ea-96e4-ad14912125db.png)
![image](https://user-images.githubusercontent.com/46949445/76089328-7ccc0780-5fca-11ea-9a39-50a1d2eda068.png)

**Comment by skinnynpale** [comment]
Отцентрируй содержимое пожалуйста
![image](https://user-images.githubusercontent.com/52371356/86579287-4e296200-bfa7-11ea-9497-3e5735e1940b.png)

**Comment by skinnynpale** [comment]
![image](https://user-images.githubusercontent.com/52371356/87121423-e88dec00-c2ac-11ea-81e3-c2ed573099a5.png)
И регистрация тоже полетела

**Comment by skinnynpale** [comment]
Можешь закрывать
