### ISSUE TITLE
bem

### ISSUE THREAD

**Issue by artamonJr** [andreylarionovdev/toxin#5]
1. Каждый блок = mixin
![image](https://user-images.githubusercontent.com/46949445/74630871-9bc63f00-516c-11ea-947b-47b6656b83b0.png)
2. Мы используем БЭМ, а что используешь тут ты?)
![image](https://user-images.githubusercontent.com/46949445/74631100-2f980b00-516d-11ea-801e-fa00d581ddba.png)
Почитай еще раз про бэм (https://ru.bem.info/methodology/quick-start/)

**Comment by madnessJs** [comment]
Мы не используем миксы
![image](https://user-images.githubusercontent.com/46949445/75035536-bd069280-54c0-11ea-8016-1606347fdeb9.png)
![image](https://user-images.githubusercontent.com/46949445/75035549-c263dd00-54c0-11ea-8680-f4625f437866.png)

Название не по бэм
![image](https://user-images.githubusercontent.com/46949445/75035601-e4f5f600-54c0-11ea-9bb1-e491091a2293.png)

И много, много таких моментов. Про бэм ты не прочитал я так понимаю. Советую тебе изучить глубоко азы именований, тк это серьезная вещь. Хорошим именованием ты помогаешь лучше ориентироваться в твоем коде другим разработчикам.

**Comment by madnessJs** [comment]
Не подходит
![image](https://user-images.githubusercontent.com/46949445/75449932-f5094c00-597e-11ea-9759-1a9086839254.png)
![image](https://user-images.githubusercontent.com/46949445/75449957-005c7780-597f-11ea-895e-9190ace6fd63.png)
![image](https://user-images.githubusercontent.com/46949445/75449986-0eaa9380-597f-11ea-8f10-d39040983c23.png)

**Comment by madnessJs** [comment]
Неправильно название элемента подобрано
![image](https://user-images.githubusercontent.com/46949445/75983707-0fe93c80-5efa-11ea-8d5b-d70f9e7f447a.png)

Вот в таких местах лучше именовать к примеру footer__text-input (чтобы название элемента совпадало с название блока). Это не обязательство, просто договоренность. Пробегись по всем местам по этому моменту
![image](https://user-images.githubusercontent.com/46949445/75983920-7c643b80-5efa-11ea-843d-fbb5a2672a24.png)

**Comment by madnessJs** [comment]
Не используй id
![image](https://user-images.githubusercontent.com/46949445/76091163-134df800-5fce-11ea-9a61-df98d4971708.png)

**Comment by madnessJs** [comment]
button_hovered не катит. Я не навел на кнопку, придумай другое название
![image](https://user-images.githubusercontent.com/46949445/76091815-56f53180-5fcf-11ea-8835-dfc7e63945dc.png)

**Comment by artamonJr** [comment]
подписаться форма?, ну)
![image](https://user-images.githubusercontent.com/46949445/78246622-1ca98200-74f2-11ea-9887-cb6c2c4cba90.png)

**Comment by artamonJr** [comment]
fluid? неверно
![image](https://user-images.githubusercontent.com/46949445/78340157-43bd8d80-759e-11ea-9561-811221df9b03.png)

тут тоже неверно. Модификатор без ключа лучше использовать только для описывания состояний блока/элемента. focused, hovered и тд. А в остальных случаях использовать ключ значение
![image](https://user-images.githubusercontent.com/46949445/78340364-a747bb00-759e-11ea-8b6a-1676cc612203.png)

**Comment by andreylarionovdev** [comment]
> тут тоже неверно. Модификатор без ключа лучше использовать только для описывания состояний блока/элемента. focused, hovered и тд. А в остальных случаях использовать ключ значение
> ![image](https://user-images.githubusercontent.com/46949445/78340364-a747bb00-759e-11ea-8b6a-1676cc612203.png)

А тут и происходит описание состояния блока. Можно изменить на dropdown_state_empty, но по-моему в данном случае это избыточная информация.

**Comment by artamonJr** [comment]
Лучше заменить на dropdown__group => dropdown__item
![image](https://user-images.githubusercontent.com/46949445/78565741-00c21b00-7827-11ea-9a98-28d3e6066dbd.png)

> А тут и происходит описание состояния блока. Можно изменить на dropdown_state_empty, но по-моему в данном случае это избыточная информация.
Не совсем это правильно как-то. Что значит empty? Пустой правильно, но после нажатия на кнопку у тебя в дропдаун ничего не пишется, поэтому говорить, что после нажатия на каунт баттон, он не пустой как-то не очень. Лучше у кнопки у самой модификатор менять при нажатии на кнопку.

**Comment by andreylarionovdev** [comment]
> Лучше заменить на dropdown__group => dropdown__item
> ![image](https://user-images.githubusercontent.com/46949445/78565741-00c21b00-7827-11ea-9a98-28d3e6066dbd.png)

“Лучше  заменить datepicker-range__row на datepicker-range__group, а datepicker-range__dropdown-group на  datepicker-range__item” или “Лучше заменить datepicker-range__dropdown-group на datepicker-range__dropdown-item”?

> Как ты переводишь модификатор и что вкладываешь в это понятие?
> ![image](https://user-images.githubusercontent.com/46949445/78567574-9199f600-7829-11ea-8cad-3dab19144e4b.png)

fluid - в данном случае имеется ввиду “изменяющийся, заполняющий всё доступное пространство”. Это снова - inspired by bootstrap) 
![Screenshot 2020-04-06 at 20 13 05](https://user-images.githubusercontent.com/53269810/78604285-dccbfd00-7859-11ea-9f38-8007b959e058.png)

> когда я вижу имя button-group я думаю, что там лежит button и это типо обертки или группирующий элемент для кнопки, а там еще и текст какой-то.

Я думаю точно так же, но только я не исключаю, что в группе могут также находиться элементы, которые логически связаны с кнопкой. Иначе, если в группе одна кнопка, то причем здесь “группа” или “группирующий элемент”?


> Подумай над переименование тут
> ![image](https://user-images.githubusercontent.com/46949445/78568368-ae82f900-782a-11ea-9406-e1ab01902650.png)
> ![image](https://user-images.githubusercontent.com/46949445/78569614-8ac0b280-782c-11ea-9b61-c96e8770e863.png)

По аналогии с вышеуказанным
> Лучше заменить на dropdown__group => dropdown__item

можно предположить, что лучшим вариантом будет заменить __sign-up-button-group на __sign-up-item

**Comment by artamonJr** [comment]
> Лучше заменить datepicker-range__row на datepicker-range__group, а datepicker-range__dropdown-group на  datepicker-range__item

Да, именно это. Не понятно написал, согласен)

А ты любитель bootstrap я гляжу, окей оставим)

> можно предположить, что лучшим вариантом будет заменить __sign-up-button-group на __sign-up-item
Лучше будет сделать __sign-up-group

**Comment by artamonJr** [comment]
С этой кнопкой поработай еще. Посмотри возможные type's у тега button
![image](https://user-images.githubusercontent.com/46949445/78989886-8a325f80-7b3d-11ea-84b0-1a82754978f8.png)

**Comment by artamonJr** [comment]
Подумай над именованием. H1 это заголовок страницы, а у тебя класс описывает его как заголовок списка. Как-то не удачно тут это сочетается
![image](https://user-images.githubusercontent.com/46949445/79109089-56934780-7d80-11ea-82f1-c18d20d8ebe5.png)

**Comment by artamonJr** [comment]
Уверен насчет focused? Ты фокусируешься на карточке номера?
![image](https://user-images.githubusercontent.com/46949445/81043633-48d26d00-8ebb-11ea-971f-7ab23c80a9eb.png)

**Comment by artamonJr** [comment]
Не очень удачное название. Переключатель навигации? Обычно эту кнопку называют burger или что-то в этом духе
![image](https://user-images.githubusercontent.com/46949445/82803262-e8ff2e80-9e88-11ea-94bb-14c8397a35e3.png)

Почему модификатор говорит, что заливка прозрачная, но по факту она белая?) Мне кажется, нужно переименовать модификатор
![image](https://user-images.githubusercontent.com/46949445/82803632-89555300-9e89-11ea-9458-d9cad664e75f.png)
