### ISSUE TITLE
html/pug

### ISSUE THREAD

**Issue by artamonJr** [andreylarionovdev/toxin#6]
1. Семантически неправильно подобран тег для КНОПКИ)
![image](https://user-images.githubusercontent.com/46949445/74631304-b5b45180-516d-11ea-86ae-5fd290fb8968.png)

2. Аналогично
![image](https://user-images.githubusercontent.com/46949445/74631340-c6fd5e00-516d-11ea-997b-85b3af382fee.png)

3. Тут явно напрашивается список
![image](https://user-images.githubusercontent.com/46949445/74631473-1ba0d900-516e-11ea-9497-bc21e83e9cb5.png)

Вот, [почитай](https://habr.com/ru/post/317728/)
И посмотри семантику в целом еще разок

**Comment by madnessJs** [comment]
Ты сделал? 
![image](https://user-images.githubusercontent.com/46949445/75035917-b0366e80-54c1-11ea-985c-b04888117b02.png)

Не видно(
1. У тебя тут элементы формы используются вне формы
![image](https://user-images.githubusercontent.com/46949445/75035908-a90f6080-54c1-11ea-8c57-70b3d1d41b64.png)
2. Тут опять какой-то непонятный тег
![image](https://user-images.githubusercontent.com/46949445/75036058-00adcc00-54c2-11ea-91e4-8bcd065e412a.png)

Убедительная просьба, проходись с исправлениями по всему проекту и еще раз пробегись по стандартам и отрефактори проект. Ты, я думаю, заинтересован в скорейшем завершении рефакторинга, поэтому это в твоих же интересах. А так приходится тратить много времени на одну и ту же проблему.

**Comment by madnessJs** [comment]
Тут aside не правильно используется
![image](https://user-images.githubusercontent.com/46949445/75450640-436b1a80-5980-11ea-8686-aa299b4dd920.png)

Dropdown как-то тоже переусложненно сделан. Ты label как обертку используешь, это не верно
![image](https://user-images.githubusercontent.com/46949445/75451138-0b180c00-5981-11ea-8bc7-94e9648a6612.png)

**Comment by madnessJs** [comment]
Это вообще что?? Почему это радио инпут?)
![image](https://user-images.githubusercontent.com/46949445/76090961-a9355300-5fcd-11ea-9dbc-e02cab0bdce3.png)

**Comment by madnessJs** [comment]
Зачем ты и в календаре и тут скрываешь input и делаешь дополнительный див?
![image](https://user-images.githubusercontent.com/46949445/76091519-c74f8300-5fce-11ea-8c8a-c2585ea1f474.png)
Можно же сделать обертку над всем этим и input будет выполнять свою функцию, а тут как-то не очень получается

**Comment by madnessJs** [comment]
Не годится содержание meta тегов
![image](https://user-images.githubusercontent.com/46949445/76091905-82781c00-5fcf-11ea-90be-3fd9317eec08.png)

**Comment by madnessJs** [comment]
Неправильное использование спецсимвола
![image](https://user-images.githubusercontent.com/46949445/76094501-ccfb9780-5fd3-11ea-848d-d617f40f0f33.png)

**Comment by andreylarionovdev** [comment]
> Это вообще что?? Почему это радио инпут?)
> ![image](https://user-images.githubusercontent.com/46949445/76090961-a9355300-5fcd-11ea-9dbc-e02cab0bdce3.png)

По-моему, всё довольно логично. В ui kit эта штуковина подписана **rate button**, потому и реализована соответствующим образом. Это не моё личное изобретение, а широко используемый элемент ui. Другое дело, что, может быть, в данном конкретном месте эти инпуты должны дизейблится, чтобы только отображать рейтинг, не давая его редактировать. Но я легко могу представить также кейс, когда по клику на звёздочку выскакивает какой нибудь popup с просьбой заполнить отзыв или что нибудь подобное. В конце концов, если рейтинг существует и отображается, значит он также должен где то выставляться) и тут то этот компонент с возможностью выставления оценки также будет как нельзя кстати)

**Comment by andreylarionovdev** [comment]
> Не годится содержание meta тегов

Самому сочинить это?)

**Comment by madnessJs** [comment]
> > Не годится содержание meta тегов
> 
> Самому сочинить это?)

Ага) Будто бы у тебя рабочий сайт

**Comment by madnessJs** [comment]
> > Это вообще что?? Почему это радио инпут?)
> > ![image](https://user-images.githubusercontent.com/46949445/76090961-a9355300-5fcd-11ea-9dbc-e02cab0bdce3.png)
> 
> По-моему, всё довольно логично. В ui kit эта штуковина подписана **rate button**, потому и реализована соответствующим образом. Это не моё личное изобретение, а широко используемый элемент ui. Другое дело, что, может быть, в данном конкретном месте эти инпуты должны дизейблится, чтобы только отображать рейтинг, не давая его редактировать. Но я легко могу представить также кейс, когда по клику на звёздочку выскакивает какой нибудь popup с просьбой заполнить отзыв или что нибудь подобное. В конце концов, если рейтинг существует и отображается, значит он также должен где то выставляться) и тут то этот компонент с возможностью выставления оценки также будет как нельзя кстати)

Ну обычно рейтинг должен проставляться уже в странице самого номера, но тут это не продумано, согласен. Кейс с pop-up'ом вполне может быть, но тогда должно быть на карточке номера, где-то указано, что мол нажмите чтобы оставить отзыв. Даже если, как ты говоришь, на звездочку мы будет нажимать, то все равно не верно сделано. Радио button's не для этого были придуманы и + у тебя элементы формы используются вне формы. Лучше тогда сделать просто баттонами и задизейблить их

**Comment by andreylarionovdev** [comment]
> Ну обычно рейтинг должен проставляться уже в странице самого номера, но тут это не продумано, согласен. Кейс с pop-up'ом вполне может быть, но тогда должно быть на карточке номера, где-то указано, что мол нажмите чтобы оставить отзыв. Даже если, как ты говоришь, на звездочку мы будет нажимать, то все равно не верно сделано. Радио button's не для этого были придуманы и + у тебя элементы формы используются вне формы. Лучше тогда сделать просто баттонами и задизейблить их

В целом, согласен. Переосмыслил уже это, исправил.

**Comment by artamonJr** [comment]
Хедер
1. Лучше всегда указывать type у button
![image](https://user-images.githubusercontent.com/46949445/78245393-131f1a80-74f0-11ea-9494-d49e62dc5287.png)
2. Почему ты сделал user-menu пунктом списка navigation? Как по мне, так оно никак не связано со списком ссылок.
![image](https://user-images.githubusercontent.com/46949445/78246072-38f8ef00-74f1-11ea-9b8a-1340e09291ed.png)
3. Напоминает мой код когда смотрю) Не нашел использования модификатора size_small. Глаза замылились наверное?)
![image](https://user-images.githubusercontent.com/46949445/78246233-81b0a800-74f1-11ea-98ea-45806b8aa399.png)

**Comment by artamonJr** [comment]
Футер
1. Может полегче придумаешь название?)
![image](https://user-images.githubusercontent.com/46949445/78246399-c2a8bc80-74f1-11ea-8330-868b0f68f6d6.png)
2. subscription-form, ну)
![image](https://user-images.githubusercontent.com/46949445/78246622-1ca98200-74f2-11ea-9887-cb6c2c4cba90.png)

**Comment by artamonJr** [comment]
head
1. Убери пробелы в description
2. toxin.com? зачем домен указал?
![image](https://user-images.githubusercontent.com/46949445/78246791-64c8a480-74f2-11ea-86a9-81b0e746295c.png)

**Comment by andreylarionovdev** [comment]
> 3. Напоминает мой код когда смотрю) Не нашел использования модификатора size_small. Глаза замылились наверное?)

Да это по-моему из официальной документации БЭМ, только _s как то слишком лаконично, поэтому _small

![Screenshot 2020-04-02 at 15 30 53](https://user-images.githubusercontent.com/53269810/78303529-1987b380-753d-11ea-88ce-8edcb7160f67.png)

> Не нашел использования модификатора size_small. Глаза замылились наверное?)
>    ![image](https://user-images.githubusercontent.com/46949445/78246233-81b0a800-74f1-11ea-98ea-45806b8aa399.png)

Ты же сам скрин вон сделал, где он используется) Кнопки в header. Если я правильно вопрос понял. Ну или если в коде, то вот:

![Screenshot 2020-04-02 at 23 59 30](https://user-images.githubusercontent.com/53269810/78304223-864f7d80-753e-11ea-922b-744b130b0cd1.png)

**Comment by andreylarionovdev** [comment]
> 2. toxin.com? зачем домен указал?
>    ![image](https://user-images.githubusercontent.com/46949445/78246791-64c8a480-74f2-11ea-86a9-81b0e746295c.png)

Да ну просто пофантазировал. Так не делают? Я в SEO не очень.

**Comment by andreylarionovdev** [comment]
> Футер
> 
> 1. Может полегче придумаешь названия?)
>    ![image](https://user-images.githubusercontent.com/46949445/78246399-c2a8bc80-74f1-11ea-8330-868b0f68f6d6.png)
>    ![image](https://user-images.githubusercontent.com/46949445/78246932-a0fc0500-74f2-11ea-96c8-47cda285ab40.png)

Тут могу предложить следующие варианты: `footer__main` - `footer__main-inner` и `footer__bottom` - `footer__bottom-inner`. Но они менее содержательны.

**Comment by artamonJr** [comment]
> > 2. Почему ты сделал user-menu пунктом списка navigation? Как по мне, так оно никак не связано со списком ссылок.
> 
> По-моему такой же элемент навигации, как и все остальные. А семантически он выделен отдельным списком.

согласен, вопрос снят

**Comment by artamonJr** [comment]
> > 1. Напоминает мой код когда смотрю) Не нашел использования модификатора size_small. Глаза замылились наверное?)
> 
> ![Screenshot 2020-04-02 at 15 30 53](https://user-images.githubusercontent.com/53269810/78303529-1987b380-753d-11ea-88ce-8edcb7160f67.png)
> 
> Да это из официальной документации БЭМ, только _s как то слишком лаконично, поэтому _small
> 
> > Не нашел использования модификатора size_small. Глаза замылились наверное?)
> > ![image](https://user-images.githubusercontent.com/46949445/78246233-81b0a800-74f1-11ea-98ea-45806b8aa399.png)
> 
> Ты же сам скрин вон сделал, где он используется) Кнопки в header. Если я правильно вопрос понял. Ну или если в коде, то вот:
> 
> ![Screenshot 2020-04-02 at 23 59 30](https://user-images.githubusercontent.com/53269810/78304223-864f7d80-753e-11ea-922b-744b130b0cd1.png)

черт, проглядел) вопрос снят

**Comment by artamonJr** [comment]
> > 1. toxin.com? зачем домен указал?
> >    ![image](https://user-images.githubusercontent.com/46949445/78246791-64c8a480-74f2-11ea-86a9-81b0e746295c.png)
> 
> Да ну просто пофантазировал. Так не делают? Я в SEO не очень.

Нет. По этим словам ты будешь ранжироваться в списке поисковых систем. И если у тебя будет домен не com, а ru, к примеру, то возможно что твой сайт обойдет определенное количество посетителей. Ну а вообще сейчас ключевые слова имеют мало значения, как яндекс и гугл говорят

**Comment by artamonJr** [comment]
> > Футер
> > 
> > 1. Может полегче придумаешь названия?)
> >    ![image](https://user-images.githubusercontent.com/46949445/78246399-c2a8bc80-74f1-11ea-8330-868b0f68f6d6.png)
> >    ![image](https://user-images.githubusercontent.com/46949445/78246932-a0fc0500-74f2-11ea-96c8-47cda285ab40.png)
> 
> Тут могу предложить следующие варианты: `footer__main` - `footer__main-inner` и `footer__bottom` - `footer__bottom-inner`. Но они менее содержательны.

не пойдут названия, не по бэм. Ну смотри, они у тебя имеют много общих стилей, поэтому я бы сделал 1 элемент, к примеру footer__container и в нижней части, просто перебил бы стили наследованием от footer__bottom-area

**Comment by artamonJr** [comment]
Почему lang=en?
![image](https://user-images.githubusercontent.com/46949445/78338519-9f3a4c00-759b-11ea-85da-c0b8fab26238.png)

**Comment by andreylarionovdev** [comment]
>  Почему main отделил в блок,

Это следствие двух предыдущих замечаний:

![Screenshot 2020-04-04 at 00 04 37](https://user-images.githubusercontent.com/53269810/78409116-296cc980-7609-11ea-9dad-c654a3b3ef91.png)
и
![Screenshot 2020-04-04 at 00 08 15](https://user-images.githubusercontent.com/53269810/78409134-3689b880-7609-11ea-8bca-9200743e6d48.png)

> почему landing-page article

Из стандартов:
![Screenshot 2020-04-04 at 00 17 32](https://user-images.githubusercontent.com/53269810/78409389-d9423700-7609-11ea-9469-03e2a49f6b9e.png)
Вроде бы соответствует описанию - смысл не теряется если этот блок сам по себе показать.

> почему маленькому кусочку текста дал привилегию сидеть в section?

Заменил на параграф

> Зачем атрибут readonly?

Чтоб руками никто ничего не вписал, это ж дропдаун, где мы сами формируем значение. Он был у меня изначально как div, но ты настаивал на том, что его стоит переделать в input. Как ещё запретить редактирование текстового инпута?

> Еще маленький ньюанс, делать или нет это на твое усмотрение, но я бы поменял хедер с бургером местами. Т.к. на маленьком экране, если ходить по сайту с клавиатуры, первым под фокус попадает бургер, что не очень понятно...

Исправил

**Comment by artamonJr** [comment]
Все отлично в целом. По landing-page верно говоришь, не теряется. Но подумай о том, что ты его встроишь к примеру на страницу одного номера, ага? Куда? Правильно, никуда, придется менять стили для встраивания, тк блок очень огромный, содержит в себе большие паддинги и тд. А вот если бы landing-page и был блоком main, то было бы намного семантичнее. Даже в названии есть слово page) Подумай об этом и напиши что думаешь. В целом можно и так оставить, но это не есть хорошо)

**Comment by artamonJr** [comment]
2 часть замечания пропустил. Маленьком опечатался я. Не должно провоцировать фокуса, а не не провоцирует
![image](https://user-images.githubusercontent.com/46949445/78567149-ea1cc380-7828-11ea-9d86-f5d704ad28c8.png)

**Comment by andreylarionovdev** [comment]
> Все отлично в целом. По landing-page верно говоришь, не теряется. Но подумай о том, что ты его встроишь к примеру на страницу одного номера, ага? Куда? Правильно, никуда, придется менять стили для встраивания, тк блок очень огромный, содержит в себе большие паддинги и тд. А вот если бы landing-page и был блоком main, то было бы намного семантичнее. Даже в названии есть слово page) Подумай об этом и напиши что думаешь. В целом можно и так оставить, но это не есть хорошо)

Кажется понял, к чему ты клонишь: раз уж определили компонент как ...-page, то нужно и выделить его как главный элемент страницы при помощи `<main>`. Да, видимо стоит исправить это.

> Ты уверен что заголовку место в form?
> ![image](https://user-images.githubusercontent.com/46949445/78568533-eab65980-782a-11ea-9fce-aee866f3b684.png)
> ![image](https://user-images.githubusercontent.com/46949445/78568568-f570ee80-782a-11ea-9cb9-229a061e1085.png)

Почему нет? В [спецификации](https://html.spec.whatwg.org/multipage/forms.html#the-form-element) указано, что форма может содержать any Flow content, кроме form. Вот пример платежной формы от MDN с заголовком (и кучей всего): https://github.com/mdn/learning-area/blob/master/html/forms/html-form-structure/payment-form.html

**Comment by artamonJr** [comment]
> Почему нет? В спецификации указано, что форма может содержать any Flow content, кроме form. Вот пример платежной формы от MDN с заголовком (и кучей всего)

Я знаю) Я имел ввиду по семантике правильно это или нет. Сейчас подумал, да твой вариант имеет место быть, оставляем.

**Comment by andreylarionovdev** [comment]
> Зачем тебе тут fieldset если ты используешь ul?
> ![image](https://user-images.githubusercontent.com/46949445/78766503-02f4b880-7992-11ea-9510-7f8116125f3f.png)

Хотя бы для того, чтобы определить заголовок (`<legend>`) для группы инпутов. Ну и на нём висят внутренние и внешние отступы, то есть он типа обертки и позиционируется.

> Не согласен что это h1 заголовок. Блок room-search может быть встроен на страницу, где уже есть заголовок h1. Будут конфликты семантики. Подумай как разрулить эту ситуацию
> ![image](https://user-images.githubusercontent.com/46949445/78769935-a1831880-7996-11ea-876c-59f0d124338c.png)

Сделал подобные блоки конфигурируемыми: теперь можно передать тэг и текст заголовка
![Screenshot 2020-04-09 at 21 48 57](https://user-images.githubusercontent.com/53269810/78934920-15631500-7aac-11ea-90d6-be05f8b8d05d.png)

**Comment by artamonJr** [comment]
> Хотя бы для того, чтобы определить заголовок для группы инпутов. Ну и на нём висят внутренние и внешние отступы, то есть он типа обертки и позиционируется.

Все верно. Т.е. он тебе нужен для того чтобы задать заголовок у группы контроллов и?

**Comment by andreylarionovdev** [comment]
> > Хотя бы для того, чтобы определить заголовок для группы инпутов. Ну и на нём висят внутренние и внешние отступы, то есть он типа обертки и позиционируется.
> 
> Все верно. Т.е. он тебе нужен для того чтобы задать заголовок у группы контроллов и?

И в целом сгруппировать эти все лэйблы и чекбоксы. Повторюсь - он позиционируется, на нём висят внутренние и внешние отступы. По-моему, в данном случае (в форме), лучше, чем в div всё это заворачивать.

**Comment by artamonJr** [comment]
>  По-моему, в данном случае (в форме), лучше, чем в div всё это заворачивать

Я с тобой полностью согласен, он тут как раз к месту, молодец. Я веду к тому, что у тебя и fieldset и ul группируют элементы. Но вместе их использовать это слишком, лучше будет внутри fieldset использовать p, к примеру. А ul оставить для моментов группировки элементов вне формы)

**Comment by artamonJr** [comment]
*name=guests-input
![image](https://user-images.githubusercontent.com/46949445/81043723-79b2a200-8ebb-11ea-842e-5dfdcf158f98.png)

**Comment by andreylarionovdev** [comment]
> Подумай, может можно упростить разметку кнопки?
> ![image](https://user-images.githubusercontent.com/46949445/81046031-2727b480-8ec0-11ea-8149-b52ac489b2d4.png)

Хм, тут минимум два элемента должно быть, учитывая то, что нужен бордер с градиентом. Ну и span совсем не лишним выглядит - удобнее контролировать переполнение. Наверное, что то можно придумать, но, думаю, тут лучше оставить как есть.
