### ISSUE TITLE
css/scss

### ISSUE THREAD

**Issue by artamonJr** [andreylarionovdev/toxin#7]
Никаких глобальных стилей кроме *, html, body
![image](https://user-images.githubusercontent.com/46949445/74632198-de3d4b00-516f-11ea-957e-eafd081c18e7.png)

**Comment by madnessJs** [comment]
Мы используем rem как единицы измерения в css, поэтому нужно изменить px -> rem

**Comment by madnessJs** [comment]
Не используем инлайновые стили
![image](https://user-images.githubusercontent.com/46949445/76091610-f6fe8b00-5fce-11ea-992e-e0297a442dbc.png)

**Comment by artamonJr** [comment]
Вот это очень и очень плохая штука для того чтобы задавать ее глобально, тк если у тебя проект перейдет под управление cms, не оберешься проблем)
![image](https://user-images.githubusercontent.com/46949445/77646278-46542d80-6f75-11ea-9407-686b24382301.png)
