### ISSUE TITLE
Шрифты

### ISSUE THREAD

**Issue by madnessJs** [andreylarionovdev/toxin#8]
1. Откуда в проектe Open Sans?
2. Зачем в fonts.scss 1 строчка?
3. Где у тебя используется quicksand-regular?
4. Не соблюден пункт
![image](https://user-images.githubusercontent.com/46949445/74633310-66245480-5172-11ea-9b4a-986cc719fe2a.png)

**Comment by madnessJs** [comment]
зачем в fonts.scss 1 строчка?

**Comment by madnessJs** [comment]
Где у тебя используется quicksand-regular?

**Comment by madnessJs** [comment]
Не соблюден пункт
![image](https://user-images.githubusercontent.com/46949445/74633310-66245480-5172-11ea-9b4a-986cc719fe2a.png)

**Comment by andreylarionovdev** [comment]
1. Open Sans полностью совпадает по Pixel Perfect с большими кириллическими заголовками в картах. Quicksand, который стоит на этих заголовках в фигме, не совпадает. Нашёл обсуждение и совет на эту тему в чате второго задания, решил применить.
![Screenshot 2020-02-19 at 02 43 02](https://user-images.githubusercontent.com/53269810/74790935-bcec7400-52c1-11ea-8afa-b4deac05684e.png)
2. Подключает шрифт Material Icon для иконок.
![Screenshot 2020-02-19 at 02 46 23](https://user-images.githubusercontent.com/53269810/74791307-cb875b00-52c2-11ea-80e6-77aa80a19ec6.png)
![Screenshot 2020-02-19 at 02 48 42](https://user-images.githubusercontent.com/53269810/74791318-d17d3c00-52c2-11ea-834b-e16d3d4b5c80.png)
![Screenshot 2020-02-19 at 02 49 57](https://user-images.githubusercontent.com/53269810/74791326-d6da8680-52c2-11ea-8d26-13308133dbd7.png)
3. Используется для отображения hex в UI Kit
![Screenshot 2020-02-19 at 02 54 40](https://user-images.githubusercontent.com/53269810/74791547-5f592700-52c3-11ea-9581-1d99abc4f8ae.png)
4. Исправил
